version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(levelname)-8s - %(asctime)s -  %(message)s"
        datefmt: "%I:%M:%S"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s - %(asctime)s"
        datefmt: "%I:%M:%S"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: ./logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: ./logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ./logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: ./logs/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: ./logs/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        mode: 'w'

root:
    level: NOTSET
    handlers: [info_file_handler] # console
    propogate: yes

loggers:
    a:
        level: INFO
        handlers: [info_file_handler]
        propogate: no
    b:
        level: WARNING
        handlers: [warn_file_handler]
        propogate: yes
    c:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propogate: no